hover card functionality expanded to more instances on the website
actifit/actifit-landingpage pull request #124
Opened 2024-12-30 09:59 UTC by sprinklepancake

all of them work, but for the report modal on the activity page we are having some issues (mentioned on trello)

2025-01-02 20:17 UTC, mcfarhat requested changes
@hassan a nice way to improve this is to include the actual user name, profile display, and link inside the component itself, so you don't need to insert additional details inside the UserHoverCard every time you want it added, and you can pass the details (username as params to the component)

2025-01-02 21:22 UTC, sprinklepancake commented
interesting, will look more into it!

2025-01-03 11:59 UTC, sprinklepancake commented
@mcfarhat tried something like this, thoughts?

2025-01-08 12:17 UTC, mcfarhat approved these changes

2025-01-08 12:22 UTC, merged